version: '3'
services:
    deepstream:
        image: deepstreamio/deepstream.io
        ports:
            - "6020:6020"
            - "6021:6021"
            - "8080:8080"
        volumes:
            - ./conf:/etc/deepstream
